apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers: 
      - image: postgres:10.0-alpine
        name: postgres
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
          - name: db-schema
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-schema
          configMap:
            name: db-schema
        