apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: "frontend-service"
    port: 80
    targetport: 80
  selector:
    app: frontend