apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata-persistent-volume-claim
spec:
  storageClassName: aws-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi