apiVersion: v1
kind: Service
metadata:
  labels: 
    app: mongodb
  name: mongodb
spec:
  type: NodePort
  ports:
  - name: "mongodb-service"
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb