apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-storage-class
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4
  iopsPerGB: "10"
  zones: us-east-2c