apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-storage-class
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4
  zones: us-east-2c
reclaimPolicy: Delete